In [1]:
import numpy as np
import sympy
from sympy.integrals.integrals import integrate

In [2]:
x = sympy.Symbol('x')
y = sympy.Symbol('y')
z = sympy.Symbol('z')
print(z.__class__ == sympy.core.symbol.Symbol)
np.set_printoptions(precision=2)
#print(dir(ArithmeticError))

True


In [3]:
print(((1/5)*z**2+2*z-1).diff(z))

0.4*z + 2


In [4]:
class operador:
    def __init__(self, cord, multi = 1):
        if cord.__class__ == sympy.core.symbol.Symbol:
            self.cord = cord
            self.multi = multi
        else:
            raise TypeError("Coloque una coordenada tipo símbolode sympy, sea serio")
        #fin if 
    #fin funcion
    def __mul__(self, other):
        if "sympy.core" in str(other.__class__):
            return self.multi*other.diff(self.cord)
        elif isinstance(other, (int, float)):
            return 0
        else:
            raise TypeError("Aplique este operador a un objeto tipo sympy.core")
        #fin if 
    #fin función
    def __rmul__(self, other):
        if isinstance(other, (int, float)):
            return operador(self.cord, other)
        else:
            raise TypeError("Por Ahora esta clase solo soporta que se multiplique escalares por detrás")
#fin clase

d_dx = operador(x)
d_dy = operador(y)
d_dz = operador(z)

In [5]:
B = [[d_dx, 0, 0], [0, d_dy, 0], [0, 0, d_dz], [0, 0.5*d_dz, 0.5*d_dy], [0.5*d_dz, 0, 0.5*d_dx], [0.5*d_dy, 0.5*d_dx, 0]]
B = np.array(B)

In [6]:
phi_minusculo = [1, x, y, z, x*y, x*z, y*z, x**2, y**2, z**2]
phi = np.array([phi_minusculo[:] + [0]*20, [0]*10 + phi_minusculo[:] + [0]*10, [0] * 20 + phi_minusculo[:]])

In [7]:
Bphi = B.dot(phi)
C = np.array(list(map(lambda q: list(map(lambda p: sympy.Symbol('C' + str(q) + str(p)), range(6))), range(6))))

In [8]:
print(Bphi)

[[0 1 0 0 y z 0 2*x 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 x 0 z 0 2*y 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 x y 0 0 2*z]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0.500000000000000 0 0.5*x 0.5*y 0 0 1.0*z 0 0
  0.500000000000000 0 0.5*x 0 0.5*z 0 1.0*y 0]
 [0 0 0 0.500000000000000 0 0.5*x 0.5*y 0 0 1.0*z 0 0 0 0 0 0 0 0 0 0 0
  0.500000000000000 0 0 0.5*y 0.5*z 0 1.0*x 0 0]
 [0 0 0.500000000000000 0 0.5*x 0 0.5*z 0 1.0*y 0 0 0.500000000000000 0 0
  0.5*y 0.5*z 0 1.0*x 0 0 0 0 0 0 0 0 0 0 0 0]]


In [9]:
print(C)

[[C00 C01 C02 C03 C04 C05]
 [C10 C11 C12 C13 C14 C15]
 [C20 C21 C22 C23 C24 C25]
 [C30 C31 C32 C33 C34 C35]
 [C40 C41 C42 C43 C44 C45]
 [C50 C51 C52 C53 C54 C55]]


In [10]:
gamma1 = (Bphi.T).dot(C).dot(Bphi)
print(gamma1)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 C00 0.5*C05 0.5*C04 C00*y + 0.5*C05*x C00*z + 0.5*C04*x
  0.5*C04*y + 0.5*C05*z 2*C00*x 1.0*C05*y 1.0*C04*z 0 0.5*C05 C01 0.5*C03
  C01*x + 0.5*C05*y 0.5*C03*x + 0.5*C05*z C01*z + 0.5*C03*y 1.0*C05*x
  2*C01*y 1.0*C03*z 0 0.5*C04 0.5*C03 C02 0.5*C03*x + 0.5*C04*y
  C02*x + 0.5*C04*z C02*y + 0.5*C03*z 1.0*C04*x 1.0*C03*y 2*C02*z]
 [0 0.5*C50 0.25*C55 0.25*C54 0.5*C50*y + 0.25*C55*x
  0.5*C50*z + 0.25*C54*x 0.25*C54*y + 0.25*C55*z 1.0*C50*x 0.5*C55*y
  0.5*C54*z 0 0.25*C55 0.5*C51 0.25*C53 0.5*C51*x + 0.25*C55*y
  0.25*C53*x + 0.25*C55*z 0.5*C51*z + 0.25*C53*y 0.5*C55*x 1.0*C51*y
  0.5*C53*z 0 0.25*C54 0.25*C53 0.5*C52 0.25*C53*x + 0.25*C54*y
  0.5*C52*x + 0.25*C54*z 0.5*C52*y + 0.25*C53*z 0.5*C54*x 0.5*C53*y
  1.0*C52*z]
 [0 0.5*C40 0.25*C45 0.25*C44 0.5*C40*y + 0.25*C45*x
  0.5*C40*z + 0.25*C44*x 0.25*C44*y + 0.25*C45*z 1.0*C40*x 0.5*C45*y
  0.5*C44*z 0 0.25*C45 0.5*C41 0.25*C43 0.5*C41*x + 0.25*C45*y
  0.25*C43*x + 0.2

In [11]:
phi_min21 = [x, x*y, x*z]
phi_min22 = [1, y, z, y*z, x**2, y**2, z**2]
phi2 = np.array([phi_min21 + [0]*20 + phi_min22, [0]*3 + phi_min22 + [0]*7 + phi_min21 + [0]*10, [0]*10 + phi_min22 + [0]*3 + phi_min21 + [0]*7])

In [12]:
print(phi2)

[[x x*y x*z 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 y z y*z x**2 y**2
  z**2]
 [0 0 0 1 y z y*z x**2 y**2 z**2 0 0 0 0 0 0 0 x x*y x*z 0 0 0 0 0 0 0 0
  0 0]
 [0 0 0 0 0 0 0 0 0 0 1 y z y*z x**2 y**2 z**2 0 0 0 x x*y x*z 0 0 0 0 0
  0 0]]


In [13]:
Bphi2 = B.dot(phi2)
print(Bphi2)

[[1 y z 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2*x 0 0]
 [0 0 0 0 1 0 z 0 2*y 0 0 0 0 0 0 0 0 0 x 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 y 0 0 2*z 0 0 0 0 0 x 0 0 0 0 0 0 0]
 [0 0 0 0 0 0.500000000000000 0.5*y 0 0 1.0*z 0 0.500000000000000 0 0.5*z
  0 1.0*y 0 0 0 0.5*x 0 0.5*x 0 0 0 0 0 0 0 0]
 [0 0 0.5*x 0 0 0 0 0 0 0 0 0 0 0 1.0*x 0 0 0 0 0 0.500000000000000 0.5*y
  0.5*z 0 0 0.500000000000000 0.5*y 0 0 1.0*z]
 [0 0.5*x 0 0 0 0 0 1.0*x 0 0 0 0 0 0 0 0 0 0.500000000000000 0.5*y 0.5*z
  0 0 0 0 0.500000000000000 0 0.5*z 0 1.0*y 0]]


In [14]:
gamma2 = (Bphi2.T).dot(C).dot(Bphi2)
E2 = (phi2.T).dot(phi2)

In [15]:
print(gamma2)

[[C00 C00*y + 0.5*C05*x C00*z + 0.5*C04*x 0 C01 0.5*C03 C01*z + 0.5*C03*y
  1.0*C05*x 2*C01*y 1.0*C03*z 0 0.5*C03 C02 C02*y + 0.5*C03*z 1.0*C04*x
  1.0*C03*y 2*C02*z 0.5*C05 C01*x + 0.5*C05*y 0.5*C03*x + 0.5*C05*z
  0.5*C04 0.5*C03*x + 0.5*C04*y C02*x + 0.5*C04*z 0 0.5*C05 0.5*C04
  0.5*C04*y + 0.5*C05*z 2*C00*x 1.0*C05*y 1.0*C04*z]
 [C00*y + 0.5*C50*x 0.5*x*(C05*y + 0.5*C55*x) + y*(C00*y + 0.5*C50*x)
  0.5*x*(C04*y + 0.5*C54*x) + z*(C00*y + 0.5*C50*x) 0 C01*y + 0.5*C51*x
  0.5*C03*y + 0.25*C53*x
  0.5*y*(C03*y + 0.5*C53*x) + z*(C01*y + 0.5*C51*x)
  1.0*x*(C05*y + 0.5*C55*x) 2*y*(C01*y + 0.5*C51*x)
  1.0*z*(C03*y + 0.5*C53*x) 0 0.5*C03*y + 0.25*C53*x C02*y + 0.5*C52*x
  y*(C02*y + 0.5*C52*x) + 0.5*z*(C03*y + 0.5*C53*x)
  1.0*x*(C04*y + 0.5*C54*x) 1.0*y*(C03*y + 0.5*C53*x)
  2*z*(C02*y + 0.5*C52*x) 0.5*C05*y + 0.25*C55*x
  x*(C01*y + 0.5*C51*x) + 0.5*y*(C05*y + 0.5*C55*x)
  0.5*x*(C03*y + 0.5*C53*x) + 0.5*z*(C05*y + 0.5*C55*x)
  0.5*C04*y + 0.25*C54*x
  0.5*x*(C03*y + 0.5*C53*x) + 0.5*y

In [16]:
print(E2)

[[x**2 x**2*y x**2*z 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 x x*y x*z
  x*y*z x**3 x*y**2 x*z**2]
 [x**2*y x**2*y**2 x**2*y*z 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 x*y
  x*y**2 x*y*z x*y**2*z x**3*y x*y**3 x*y*z**2]
 [x**2*z x**2*y*z x**2*z**2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 x*z
  x*y*z x*z**2 x*y*z**2 x**3*z x*y**2*z x*z**3]
 [0 0 0 1 y z y*z x**2 y**2 z**2 0 0 0 0 0 0 0 x x*y x*z 0 0 0 0 0 0 0 0
  0 0]
 [0 0 0 y y**2 y*z y**2*z x**2*y y**3 y*z**2 0 0 0 0 0 0 0 x*y x*y**2
  x*y*z 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 z y*z z**2 y*z**2 x**2*z y**2*z z**3 0 0 0 0 0 0 0 x*z x*y*z
  x*z**2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 y*z y**2*z y*z**2 y**2*z**2 x**2*y*z y**3*z y*z**3 0 0 0 0 0 0 0
  x*y*z x*y**2*z x*y*z**2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 x**2 x**2*y x**2*z x**2*y*z x**4 x**2*y**2 x**2*z**2 0 0 0 0 0 0
  0 x**3 x**3*y x**3*z 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 y**2 y**3 y**2*z y**3*z x**2*y**2 y**4 y**2*z**2 0 0 0 0 0 0 0
  x*y**2 x*y**3 x*y**2*z 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 z**2 y*z**2 z**3 y*z*

In [17]:
phi_minim = [1, x, y, z]
phi3 = np.array([phi_minim + [0]*8, [0]*4 + phi_minim + [0]*4, [0]*8 + phi_minim])
Bphi3 = B.dot(phi3)
gamma3 = (Bphi3.T).dot(C).dot(Bphi3)
print(phi3)
print(Bphi3)

[[1 x y z 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 x y z 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 x y z]]
[[0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0.500000000000000 0 0 0.500000000000000 0]
 [0 0 0 0.500000000000000 0 0 0 0 0 0.500000000000000 0 0]
 [0 0 0.500000000000000 0 0 0.500000000000000 0 0 0 0 0 0]]


In [18]:
print(gamma3)

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 C00 0.5*C05 0.5*C04 0 0.5*C05 C01 0.5*C03 0 0.5*C04 0.5*C03 C02]
 [0 0.5*C50 0.25*C55 0.25*C54 0 0.25*C55 0.5*C51 0.25*C53 0 0.25*C54
  0.25*C53 0.5*C52]
 [0 0.5*C40 0.25*C45 0.25*C44 0 0.25*C45 0.5*C41 0.25*C43 0 0.25*C44
  0.25*C43 0.5*C42]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0.5*C50 0.25*C55 0.25*C54 0 0.25*C55 0.5*C51 0.25*C53 0 0.25*C54
  0.25*C53 0.5*C52]
 [0 C10 0.5*C15 0.5*C14 0 0.5*C15 C11 0.5*C13 0 0.5*C14 0.5*C13 C12]
 [0 0.5*C30 0.25*C35 0.25*C34 0 0.25*C35 0.5*C31 0.25*C33 0 0.25*C34
  0.25*C33 0.5*C32]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0.5*C40 0.25*C45 0.25*C44 0 0.25*C45 0.5*C41 0.25*C43 0 0.25*C44
  0.25*C43 0.5*C42]
 [0 0.5*C30 0.25*C35 0.25*C34 0 0.25*C35 0.5*C31 0.25*C33 0 0.25*C34
  0.25*C33 0.5*C32]
 [0 C20 0.5*C25 0.5*C24 0 0.5*C25 C21 0.5*C23 0 0.5*C24 0.5*C23 C22]]


In [19]:
integral = np.vectorize(lambda p: integrate(integrate(integrate(p, (x, -1, 1)),(y, -1, 1)), (z, -1, 1)) )

In [20]:
gamma_final1 = integral(gamma1)
gamma_final2 = integral(gamma2)

In [21]:
print(gamma_final1)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 8*C00 4.0*C05 4.0*C04 0 0 0 0 0 0 0 4.0*C05 8*C01 4.0*C03 0 0 0 0 0 0
  0 4.0*C04 4.0*C03 8*C02 0 0 0 0 0 0]
 [0 4.0*C50 2.0*C55 2.0*C54 0 0 0 0 0 0 0 2.0*C55 4.0*C51 2.0*C53 0 0 0 0
  0 0 0 2.0*C54 2.0*C53 4.0*C52 0 0 0 0 0 0]
 [0 4.0*C40 2.0*C45 2.0*C44 0 0 0 0 0 0 0 2.0*C45 4.0*C41 2.0*C43 0 0 0 0
  0 0 0 2.0*C44 2.0*C43 4.0*C42 0 0 0 0 0 0]
 [0 0 0 0 2.66666666666667*C00 + 0.666666666666667*C55
  0.666666666666667*C54 1.33333333333333*C04 2.66666666666667*C50
  2.66666666666667*C05 0 0 0 0 0
  1.33333333333333*C05 + 1.33333333333333*C51 0.666666666666667*C53
  1.33333333333333*C03 1.33333333333333*C55 5.33333333333333*C01 0 0 0 0
  0 1.33333333333333*C04 + 0.666666666666667*C53 1.33333333333333*C52
  2.66666666666667*C02 1.33333333333333*C54 2.66666666666667*C03 0]
 [0 0 0 0 0.666666666666667*C45
  2.66666666666667*C00 + 0.666666666666667*C44 1.33333333333333*C05
  2.66666666666667*C40 0 2.66666666666667*C04 0 0 0 0

In [22]:
print(gamma_final2)

[[8*C00 0 0 0 8*C01 4.0*C03 0 0 0 0 0 4.0*C03 8*C02 0 0 0 0 4.0*C05 0 0
  4.0*C04 0 0 0 4.0*C05 4.0*C04 0 0 0 0]
 [0 2.66666666666667*C00 + 0.666666666666667*C55 0.666666666666667*C54 0
  0 0 1.33333333333333*C03 1.33333333333333*C55 5.33333333333333*C01 0 0
  0 0 2.66666666666667*C02 1.33333333333333*C54 2.66666666666667*C03 0 0
  1.33333333333333*C05 + 1.33333333333333*C51 0.666666666666667*C53 0
  1.33333333333333*C04 + 0.666666666666667*C53 1.33333333333333*C52 0 0 0
  1.33333333333333*C04 2.66666666666667*C50 2.66666666666667*C05 0]
 [0 0.666666666666667*C45 2.66666666666667*C00 + 0.666666666666667*C44 0
  0 0 2.66666666666667*C01 1.33333333333333*C45 0 2.66666666666667*C03 0
  0 0 1.33333333333333*C03 1.33333333333333*C44 0 5.33333333333333*C02 0
  1.33333333333333*C41 1.33333333333333*C05 + 0.666666666666667*C43 0
  0.666666666666667*C43 1.33333333333333*C04 + 1.33333333333333*C42 0 0 0
  1.33333333333333*C05 2.66666666666667*C40 0 2.66666666666667*C04]
 [0 0 0 0 0 0 0 0 0 0 0 0

In [23]:
E_final2 = integral(E2)

In [24]:
print(E_final2)

[[8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8 0 0 0 8/3 8/3 8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 8/5 8/9 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 8/9 8/5 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 8/9 8/9 8/5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 8 0 0 0 8/3 8/3 8/3 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 8/5 8/9 8/9 0 0 0 0 0 0 0 0 0 0 

In [25]:
print(E_final2[-13:, -13:])

[[8/3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 8/9 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 8/9 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 8/9 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 8/9 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 8 0 0 0 8/3 8/3 8/3]
 [0 0 0 0 0 0 0 8/3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 8/3 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 8/9 0 0 0]
 [0 0 0 0 0 0 8/3 0 0 0 8/5 8/9 8/9]
 [0 0 0 0 0 0 8/3 0 0 0 8/9 8/5 8/9]
 [0 0 0 0 0 0 8/3 0 0 0 8/9 8/9 8/5]]


In [27]:
print(E_final2[:17, :17])

[[8/3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 8/9 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8 0 0 0 8/3 8/3 8/3 0 0 0 0 0 0 0]
 [0 0 0 0 8/3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 8/3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 8/9 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 8/5 8/9 8/9 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 8/9 8/5 8/9 0 0 0 0 0 0 0]
 [0 0 0 8/3 0 0 0 8/9 8/9 8/5 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 8 0 0 0 8/3 8/3 8/3]
 [0 0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 8/9 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 8/5 8/9 8/9]
 [0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 8/9 8/5 8/9]
 [0 0 0 0 0 0 0 0 0 0 8/3 0 0 0 8/9 8/9 8/5]]


In [28]:
print(E_final2[-13:, :17])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [29]:
print(E_final2[:17, -13:])

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [30]:
print(gamma_final2[-13:, :17])

[[4.0*C50 0 0 0 4.0*C51 2.0*C53 0 0 0 0 0 2.0*C53 4.0*C52 0 0 0 0]
 [0 1.33333333333333*C15 + 1.33333333333333*C50 1.33333333333333*C14 0 0
  0 0.666666666666667*C53 2.66666666666667*C15 2.66666666666667*C51 0 0 0
  0 1.33333333333333*C52 2.66666666666667*C14 1.33333333333333*C53 0]
 [0 0.666666666666667*C35 0.666666666666667*C34 + 1.33333333333333*C50 0
  0 0 1.33333333333333*C51 1.33333333333333*C35 0 1.33333333333333*C53 0
  0 0 0.666666666666667*C53 1.33333333333333*C34 0 2.66666666666667*C52]
 [4.0*C40 0 0 0 4.0*C41 2.0*C43 0 0 0 0 0 2.0*C43 4.0*C42 0 0 0 0]
 [0 0.666666666666667*C35 + 1.33333333333333*C40 0.666666666666667*C34 0
  0 0 0.666666666666667*C43 1.33333333333333*C35 2.66666666666667*C41 0 0
  0 0 1.33333333333333*C42 1.33333333333333*C34 1.33333333333333*C43 0]
 [0 1.33333333333333*C25 1.33333333333333*C24 + 1.33333333333333*C40 0 0
  0 1.33333333333333*C41 2.66666666666667*C25 0 1.33333333333333*C43 0 0
  0 0.666666666666667*C43 2.66666666666667*C24 0 2.66666666666667